# Generated by Django 5.1.5 on 2025-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время записи')),
                ('car_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка авто')),
                ('car_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год авто')),
                ('car_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер авто')),
                ('vin_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN код авто')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус записи')),
            ],
            options={
                'verbose_name': 'Запись на услугу',
                'verbose_name_plural': 'Записи на услуги',
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date_time', models.DateTimeField(verbose_name='Новая дата и время')),
                ('comment', models.TextField(verbose_name='Комментарий мастера')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос на перенос услуги',
                'verbose_name_plural': 'Запросы на перенос услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Время выполнения')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name'],
            },
        ),
    ]
