# Generated by Django 5.1.5 on 2025-03-11 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_images', verbose_name='Изображение')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стартовая цена')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая цена')),
                ('bid_step', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Шаг ставки')),
                ('auction_type', models.CharField(choices=[('live', 'Live'), ('fixed_time', 'Fixed Time')], max_length=20, verbose_name='Тип аукциона')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction', verbose_name='Аукцион')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
        ),
    ]
