# Generated by Django 5.1.5 on 2025-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'Лот аукциона', 'verbose_name_plural': 'Лоты аукциона'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Ставка', 'verbose_name_plural': 'Ставки'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('live', 'Live'), ('fixed_time', 'Фиксированный')], max_length=20, verbose_name='Тип аукциона'),
        ),
    ]
