# Generated by Django 5.1.5 on 2025-03-11 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_winner_alter_auction_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images', verbose_name='Фото')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.auction', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Фото лота',
                'verbose_name_plural': 'Фото лотов',
            },
        ),
    ]
