# Generated by Django 5.1.5 on 2025-03-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auctionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('completed', 'Завершён'), ('change_requested', 'Запрос на изменение')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(upload_to='auction_images/', verbose_name='Фото'),
        ),
    ]
