# Generated by Django 5.1.5 on 2025-04-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_admin_comment_alter_auction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Победитель уведомлен'),
        ),
    ]
