# Generated by Django 5.1.5 on 2025-04-15 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала'),
        ),
    ]
